/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedIngredientsRouteImport } from './routes/_authed/ingredients'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes/index'
import { Route as AuthedPlansIndexRouteImport } from './routes/_authed/plans/index'
import { Route as AuthedRecipesNewRouteImport } from './routes/_authed/recipes/new'
import { Route as AuthedPlansPlanIdRouteImport } from './routes/_authed/plans/$planId'
import { Route as AuthedRecipesRecipeIdIndexRouteImport } from './routes/_authed/recipes/$recipeId.index'
import { Route as AuthedRecipesRecipeIdEditRouteImport } from './routes/_authed/recipes/$recipeId.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIngredientsRoute = AuthedIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansIndexRoute = AuthedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesNewRoute = AuthedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansPlanIdRoute = AuthedPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesRecipeIdIndexRoute =
  AuthedRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRecipesRecipeIdEditRoute =
  AuthedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/ingredients': typeof AuthedIngredientsRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/plans/': typeof AuthedPlansIndexRoute
  '/recipes/': typeof AuthedRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/ingredients': typeof AuthedIngredientsRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof AuthedIndexRoute
  '/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/recipes/new': typeof AuthedRecipesNewRoute
  '/plans': typeof AuthedPlansIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
  '/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/ingredients': typeof AuthedIngredientsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/_authed/recipes/new': typeof AuthedRecipesNewRoute
  '/_authed/plans/': typeof AuthedPlansIndexRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
  '/_authed/recipes/$recipeId/edit': typeof AuthedRecipesRecipeIdEditRoute
  '/_authed/recipes/$recipeId/': typeof AuthedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/ingredients'
    | '/settings'
    | '/auth/verify'
    | '/plans/$planId'
    | '/recipes/new'
    | '/plans/'
    | '/recipes/'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/ingredients'
    | '/settings'
    | '/auth/verify'
    | '/'
    | '/plans/$planId'
    | '/recipes/new'
    | '/plans'
    | '/recipes'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/ingredients'
    | '/_authed/settings'
    | '/auth/verify'
    | '/_authed/'
    | '/_authed/plans/$planId'
    | '/_authed/recipes/new'
    | '/_authed/plans/'
    | '/_authed/recipes/'
    | '/_authed/recipes/$recipeId/edit'
    | '/_authed/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ingredients': {
      id: '/_authed/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AuthedIngredientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/': {
      id: '/_authed/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthedPlansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/new': {
      id: '/_authed/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthedRecipesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/$planId': {
      id: '/_authed/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AuthedPlansPlanIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId/': {
      id: '/_authed/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AuthedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/$recipeId/edit': {
      id: '/_authed/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIngredientsRoute: typeof AuthedIngredientsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPlansPlanIdRoute: typeof AuthedPlansPlanIdRoute
  AuthedRecipesNewRoute: typeof AuthedRecipesNewRoute
  AuthedPlansIndexRoute: typeof AuthedPlansIndexRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
  AuthedRecipesRecipeIdEditRoute: typeof AuthedRecipesRecipeIdEditRoute
  AuthedRecipesRecipeIdIndexRoute: typeof AuthedRecipesRecipeIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIngredientsRoute: AuthedIngredientsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPlansPlanIdRoute: AuthedPlansPlanIdRoute,
  AuthedRecipesNewRoute: AuthedRecipesNewRoute,
  AuthedPlansIndexRoute: AuthedPlansIndexRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
  AuthedRecipesRecipeIdEditRoute: AuthedRecipesRecipeIdEditRoute,
  AuthedRecipesRecipeIdIndexRoute: AuthedRecipesRecipeIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
